Feature/copy button updates
zesty-io/design-system pull request #149
Opened 2021-08-25 17:20 UTC by d88naimi

adding outlinedSmall button style for copyButton 

https://www.screencast.com/t/F5vHOEUiTM8J

2021-08-29 20:22 UTC, ardeay commented
@d88naimi I watched the movie, please add screenshots of both the button dark and light states the PR comment, and whatever was there as a comparison

2021-09-03 18:59 UTC, shrunyan requested changes
- can not use `opacity` as it will not work well with all backgrounds.
- superfluous usage of background-color with bgd-function(). Use one or the other.
- need to chose either `warn` or `destructive`
- lets not have a `tertiary` class, as this should be the "default" styling of all buttonss.
- remove `transition: all 0.3s ease;`

2021-09-07 19:13 UTC, d88naimi commented
@shrunyan updated with all changes requested, when removing opacity from the buttons I used a color-picker extension for disabled buttons. Will make a video and attach to PR in manager-ui https://github.com/zesty-io/manager-ui/pull/887

2021-09-08 18:53 UTC, shrunyan approved these changes

2021-09-08 20:07 UTC, merged